/**
 * seed/tech-list.ts
 *
 * Kanoniczne 500 technologii z metadanymi startowymi.
 * GitHub API uzupełni: stars, forks, last_release.
 * npm API uzupełni: weekly_downloads.
 *
 * Pola ręczne (nie da się automatycznie wyciągnąć):
 *   - category_slug, ecosystem, tagline
 *
 * Format: { slug, name, github, npm?, category_slug, ecosystem[], tagline }
 *   github: "owner/repo" — do GitHub API query
 *   npm:    "package-name" — do npm Registry query (null jeśli nie ma)
 */

export type TechSeed = {
  slug:          string
  name:          string
  github:        string | null   // "facebook/react"
  npm:           string | null   // "@scope/pkg" lub "pkg"
  category_slug: string
  ecosystem:     string[]
  tagline:       string
  website_url?:  string
  license?:      string
  language?:     string          // główny język (dla filtrów)
}

export const TECH_LIST: TechSeed[] = [
  // ─── JĘZYKI PROGRAMOWANIA ─────────────────
  { slug: 'python',       name: 'Python',       github: 'python/cpython',          npm: null,            category_slug: 'languages', ecosystem: ['backend','data','ml','scripting'],  tagline: 'Wszechstronny język wysokiego poziomu znany z czytelności kodu i ogromnego ekosystemu bibliotek.', website_url: 'https://python.org', license: 'PSF', language: 'C' },
  { slug: 'javascript',   name: 'JavaScript',   github: 'nicolo-ribaudo/tc39-proposal-type-annotations', npm: null, category_slug: 'languages', ecosystem: ['frontend','backend','mobile','scripting'], tagline: 'Język skryptowy napędzający interaktywność stron WWW oraz aplikacje serwerowe przez Node.js.', website_url: 'https://developer.mozilla.org', license: 'MIT', language: 'JavaScript' },
  { slug: 'typescript',   name: 'TypeScript',   github: 'microsoft/TypeScript',    npm: 'typescript',    category_slug: 'languages', ecosystem: ['frontend','backend','mobile'],      tagline: 'Nadzbiór JavaScript z opcjonalnym typowaniem statycznym, rozwijany przez Microsoft.', website_url: 'https://www.typescriptlang.org', license: 'Apache-2.0', language: 'TypeScript' },
  { slug: 'rust',         name: 'Rust',         github: 'rust-lang/rust',          npm: null,            category_slug: 'languages', ecosystem: ['systems','backend','wasm','cli'],   tagline: 'Systemowy język programowania zaprojektowany pod kątem bezpieczeństwa pamięci i wysokiej wydajności.', website_url: 'https://www.rust-lang.org', license: 'MIT', language: 'Rust' },
  { slug: 'go',           name: 'Go',           github: 'golang/go',               npm: null,            category_slug: 'languages', ecosystem: ['backend','devops','cli','cloud'],   tagline: 'Kompilowany język Google z prostą składnią, natywną współbieżnością i błyskawicznym czasem kompilacji.', website_url: 'https://go.dev', license: 'BSD-3', language: 'Go' },
  { slug: 'java',         name: 'Java',         github: 'openjdk/jdk',             npm: null,            category_slug: 'languages', ecosystem: ['backend','enterprise','mobile','android'], tagline: 'Obiektowy język z zasadą "write once, run anywhere", dominujący w enterprise i Androidzie.', website_url: 'https://java.com', license: 'GPL-2.0', language: 'Java' },
  { slug: 'kotlin',       name: 'Kotlin',       github: 'JetBrains/kotlin',        npm: null,            category_slug: 'languages', ecosystem: ['backend','android','mobile'],       tagline: 'Nowoczesny język JVM od JetBrains, oficjalny język Androida, w pełni interoperacyjny z Java.', website_url: 'https://kotlinlang.org', license: 'Apache-2.0', language: 'Kotlin' },
  { slug: 'swift',        name: 'Swift',        github: 'swiftlang/swift',         npm: null,            category_slug: 'languages', ecosystem: ['ios','macos','mobile'],             tagline: 'Szybki i bezpieczny język Apple do budowania aplikacji na iOS, macOS i inne platformy Apple.', website_url: 'https://swift.org', license: 'Apache-2.0', language: 'Swift' },
  { slug: 'csharp',       name: 'C#',           github: 'dotnet/roslyn',           npm: null,            category_slug: 'languages', ecosystem: ['backend','games','enterprise','windows'], tagline: 'Obiektowy język Microsoft z silnym typowaniem, główny język platformy .NET i Unity.', website_url: 'https://learn.microsoft.com/dotnet/csharp', license: 'MIT', language: 'C#' },
  { slug: 'php',          name: 'PHP',          github: 'php/php-src',             npm: null,            category_slug: 'languages', ecosystem: ['backend','web','cms'],             tagline: 'Najpopularniejszy język po stronie serwera WWW, napędzający ponad 75% stron na świecie.', website_url: 'https://www.php.net', license: 'PHP-3.01', language: 'C' },
  { slug: 'ruby',         name: 'Ruby',         github: 'ruby/ruby',               npm: null,            category_slug: 'languages', ecosystem: ['backend','scripting','web'],        tagline: 'Ekspresywny język z filozofią "developer happiness", znany z frameworka Ruby on Rails.', website_url: 'https://www.ruby-lang.org', license: 'Ruby', language: 'C' },
  { slug: 'scala',        name: 'Scala',        github: 'scala/scala',             npm: null,            category_slug: 'languages', ecosystem: ['backend','data','functional'],      tagline: 'Hybrydowy język funkcyjno-obiektowy na JVM, popularny w big data i systemach rozproszonych.', website_url: 'https://www.scala-lang.org', license: 'Apache-2.0', language: 'Scala' },
  { slug: 'elixir',       name: 'Elixir',       github: 'elixir-lang/elixir',      npm: null,            category_slug: 'languages', ecosystem: ['backend','realtime','functional'], tagline: 'Funkcyjny język na VM Erlanga, znany z odporności na błędy i skalowalności w czasie rzeczywistym.', website_url: 'https://elixir-lang.org', license: 'Apache-2.0', language: 'Elixir' },
  { slug: 'haskell',      name: 'Haskell',      github: 'ghc/ghc',                 npm: null,            category_slug: 'languages', ecosystem: ['functional','research'],            tagline: 'Czysty język funkcyjny z silnym systemem typów, wpływający na projekt innych języków.', website_url: 'https://www.haskell.org', license: 'BSD-3', language: 'Haskell' },
  { slug: 'dart',         name: 'Dart',         github: 'dart-lang/sdk',           npm: null,            category_slug: 'languages', ecosystem: ['mobile','frontend','flutter'],      tagline: 'Język Google zoptymalizowany pod kątem szybkiego UI, głównie używany z frameworkiem Flutter.', website_url: 'https://dart.dev', license: 'BSD-3', language: 'Dart' },
  { slug: 'r',            name: 'R',            github: 'wch/r-source',            npm: null,            category_slug: 'languages', ecosystem: ['data','statistics','ml'],           tagline: 'Środowisko obliczeniowe i język dla statystyki, wizualizacji danych i uczenia maszynowego.', website_url: 'https://www.r-project.org', license: 'GPL-2.0', language: 'R' },
  { slug: 'julia',        name: 'Julia',        github: 'JuliaLang/julia',         npm: null,            category_slug: 'languages', ecosystem: ['data','ml','scientific'],           tagline: 'Wysokowydajny język do obliczeń naukowych, łączy prędkość C z prostotą Pythona.', website_url: 'https://julialang.org', license: 'MIT', language: 'Julia' },
  { slug: 'lua',          name: 'Lua',          github: 'lua/lua',                 npm: null,            category_slug: 'languages', ecosystem: ['scripting','games','embedded'],     tagline: 'Lekki język skryptowy wbudowany w gry, edytory i systemy embedded (Roblox, Redis, Neovim).', website_url: 'https://www.lua.org', license: 'MIT', language: 'C' },
  { slug: 'zig',          name: 'Zig',          github: 'ziglang/zig',             npm: null,            category_slug: 'languages', ecosystem: ['systems','embedded','wasm'],        tagline: 'Nowy systemowy język zaprojektowany jako bezpieczna alternatywa dla C, bez ukrytych alokacji.', website_url: 'https://ziglang.org', license: 'MIT', language: 'Zig' },

  // ─── FRAMEWORKI FRONTEND ─────────────────
  { slug: 'react',        name: 'React',        github: 'facebook/react',          npm: 'react',         category_slug: 'frontend', ecosystem: ['frontend','mobile','ui'],           tagline: 'Biblioteka JavaScript Facebooka do budowania interaktywnych UI z komponentowym modelem.', website_url: 'https://react.dev', license: 'MIT', language: 'JavaScript' },
  { slug: 'vue',          name: 'Vue.js',       github: 'vuejs/core',              npm: 'vue',           category_slug: 'frontend', ecosystem: ['frontend','ui'],                    tagline: 'Progresywny framework JavaScript o łagodnej krzywej uczenia, idealny do stopniowego wdrożenia.', website_url: 'https://vuejs.org', license: 'MIT', language: 'TypeScript' },
  { slug: 'angular',      name: 'Angular',      github: 'angular/angular',         npm: '@angular/core', category_slug: 'frontend', ecosystem: ['frontend','enterprise','ui'],       tagline: 'Kompletny framework Google do budowania enterprise SPA z TypeScriptem i wstrzykiwaniem zależności.', website_url: 'https://angular.dev', license: 'MIT', language: 'TypeScript' },
  { slug: 'svelte',       name: 'Svelte',       github: 'sveltejs/svelte',         npm: 'svelte',        category_slug: 'frontend', ecosystem: ['frontend','ui','compiler'],         tagline: 'Kompilowany framework UI bez Virtual DOM — przekształca komponenty w optymalne vanilla JS.', website_url: 'https://svelte.dev', license: 'MIT', language: 'JavaScript' },
  { slug: 'solidjs',      name: 'Solid.js',     github: 'solidjs/solid',           npm: 'solid-js',      category_slug: 'frontend', ecosystem: ['frontend','ui'],                    tagline: 'Reaktywna biblioteka UI bez Virtual DOM — fine-grained reactivity dla maksymalnej wydajności.', website_url: 'https://www.solidjs.com', license: 'MIT', language: 'TypeScript' },
  { slug: 'qwik',         name: 'Qwik',         github: 'QwikDev/qwik',            npm: '@builder.io/qwik', category_slug: 'frontend', ecosystem: ['frontend','ui','resumability'], tagline: 'Framework z resumability zamiast hydration — O(1) czas ładowania niezależnie od rozmiaru aplikacji.', website_url: 'https://qwik.dev', license: 'MIT', language: 'TypeScript' },
  { slug: 'astro',        name: 'Astro',        github: 'withastro/astro',         npm: 'astro',         category_slug: 'frontend', ecosystem: ['frontend','ssg','islands'],         tagline: 'Framework do budowania szybkich stron z architekturą Islands — zero JS domyślnie.', website_url: 'https://astro.build', license: 'MIT', language: 'TypeScript' },
  { slug: 'htmx',         name: 'HTMX',         github: 'bigskysoftware/htmx',     npm: 'htmx.org',      category_slug: 'frontend', ecosystem: ['frontend','hypermedia'],            tagline: 'Biblioteka rozszerzająca HTML o AJAX, WebSockets i SSE — bez pisania JavaScript.', website_url: 'https://htmx.org', license: 'BSD-2', language: 'JavaScript' },

  // ─── META-FRAMEWORKI ─────────────────────
  { slug: 'nextjs',       name: 'Next.js',      github: 'vercel/next.js',          npm: 'next',          category_slug: 'meta-frameworks', ecosystem: ['frontend','backend','fullstack','ssr'], tagline: 'Najpopularniejszy meta-framework React z SSR, ISR, App Router i pełnym wsparciem dla edge.', website_url: 'https://nextjs.org', license: 'MIT', language: 'TypeScript' },
  { slug: 'nuxtjs',       name: 'Nuxt',         github: 'nuxt/nuxt',               npm: 'nuxt',          category_slug: 'meta-frameworks', ecosystem: ['frontend','backend','fullstack','ssr'], tagline: 'Meta-framework Vue.js z SSR, file-based routing i auto-importami komponentów.', website_url: 'https://nuxt.com', license: 'MIT', language: 'TypeScript' },
  { slug: 'sveltekit',    name: 'SvelteKit',    github: 'sveltejs/kit',            npm: '@sveltejs/kit', category_slug: 'meta-frameworks', ecosystem: ['frontend','backend','fullstack'], tagline: 'Oficjalny meta-framework Svelte z file-based routing, SSR i adapapterami dla różnych hostingów.', website_url: 'https://kit.svelte.dev', license: 'MIT', language: 'JavaScript' },
  { slug: 'remix',        name: 'Remix',        github: 'remix-run/remix',         npm: '@remix-run/node', category_slug: 'meta-frameworks', ecosystem: ['frontend','backend','fullstack'], tagline: 'Full-stack framework React skupiony na web standards, nested routes i progressive enhancement.', website_url: 'https://remix.run', license: 'MIT', language: 'TypeScript' },
  { slug: 'gatsby',       name: 'Gatsby',       github: 'gatsbyjs/gatsby',         npm: 'gatsby',        category_slug: 'meta-frameworks', ecosystem: ['frontend','ssg'],               tagline: 'SSG/SSR framework React z bogatym ekosystemem pluginów do CMS i API.', website_url: 'https://www.gatsbyjs.com', license: 'MIT', language: 'JavaScript' },
  { slug: 'tanstack-start', name: 'TanStack Start', github: 'TanStack/router',     npm: '@tanstack/react-router', category_slug: 'meta-frameworks', ecosystem: ['frontend','fullstack'], tagline: 'Pełno-stackowy framework z type-safe routing i server functions od twórców TanStack Query.', website_url: 'https://tanstack.com/start', license: 'MIT', language: 'TypeScript' },

  // ─── CSS / STYLING ────────────────────────
  { slug: 'tailwindcss',  name: 'Tailwind CSS', github: 'tailwindlabs/tailwindcss', npm: 'tailwindcss',  category_slug: 'css', ecosystem: ['frontend','css','styling'],         tagline: 'Utility-first framework CSS — compose design systemów przez klasy pomocnicze zamiast pisania CSS.', website_url: 'https://tailwindcss.com', license: 'MIT', language: 'JavaScript' },
  { slug: 'shadcn-ui',    name: 'shadcn/ui',    github: 'shadcn-ui/ui',            npm: null,            category_slug: 'css', ecosystem: ['frontend','ui','components'],       tagline: 'Kolekcja re-używalnych komponentów budowanych na Radix UI i Tailwind CSS — kopiujesz, nie instalujesz.', website_url: 'https://ui.shadcn.com', license: 'MIT', language: 'TypeScript' },
  { slug: 'bootstrap',    name: 'Bootstrap',    github: 'twbs/bootstrap',          npm: 'bootstrap',     category_slug: 'css', ecosystem: ['frontend','css','ui'],              tagline: 'Najszerzej używany framework CSS/JS z gotowymi komponentami i responsywnym gridem.', website_url: 'https://getbootstrap.com', license: 'MIT', language: 'JavaScript' },

  // ─── BACKEND NODE.JS ──────────────────────
  { slug: 'expressjs',    name: 'Express',      github: 'expressjs/express',       npm: 'express',       category_slug: 'backend', ecosystem: ['backend','nodejs','api'],           tagline: 'Minimalistyczny framework webowy Node.js — de facto standard dla REST API i middleware.', website_url: 'https://expressjs.com', license: 'MIT', language: 'JavaScript' },
  { slug: 'nestjs',       name: 'NestJS',       github: 'nestjs/nest',             npm: '@nestjs/core',  category_slug: 'backend', ecosystem: ['backend','nodejs','enterprise'],    tagline: 'Framework Node.js inspirowany Angularem — dekoratywna architektura, DI i pełna struktura.', website_url: 'https://nestjs.com', license: 'MIT', language: 'TypeScript' },
  { slug: 'fastify',      name: 'Fastify',      github: 'fastify/fastify',         npm: 'fastify',       category_slug: 'backend', ecosystem: ['backend','nodejs','api'],           tagline: 'Najszybszy framework webowy Node.js — do 76k req/s, schema-based validation i pluginy.', website_url: 'https://fastify.dev', license: 'MIT', language: 'JavaScript' },
  { slug: 'hono',         name: 'Hono',         github: 'honojs/hono',             npm: 'hono',          category_slug: 'backend', ecosystem: ['backend','edge','cloudflare'],      tagline: 'Ultra-lekki framework webowy działający na każdym JavaScript runtime: Edge, Deno, Bun, Node.js.', website_url: 'https://hono.dev', license: 'MIT', language: 'TypeScript' },
  { slug: 'trpc',         name: 'tRPC',         github: 'trpc/trpc',               npm: '@trpc/server',  category_slug: 'backend', ecosystem: ['backend','frontend','fullstack'],   tagline: 'End-to-end type-safe API bez schematu GraphQL ani OpenAPI — TypeScript jako kontrakt.', website_url: 'https://trpc.io', license: 'MIT', language: 'TypeScript' },

  // ─── BACKEND PYTHON ──────────────────────
  { slug: 'django',       name: 'Django',       github: 'django/django',           npm: null,            category_slug: 'backend', ecosystem: ['backend','python','web','cms'],     tagline: '"Batteries included" framework Python z ORM, adminem i pełną strukturą dla web aplikacji.', website_url: 'https://www.djangoproject.com', license: 'BSD-3', language: 'Python' },
  { slug: 'fastapi',      name: 'FastAPI',      github: 'fastapi/fastapi',         npm: null,            category_slug: 'backend', ecosystem: ['backend','python','api','ml'],      tagline: 'Nowoczesny, szybki framework Python do budowania API z automatyczną dokumentacją OpenAPI.', website_url: 'https://fastapi.tiangolo.com', license: 'MIT', language: 'Python' },
  { slug: 'flask',        name: 'Flask',        github: 'pallets/flask',           npm: null,            category_slug: 'backend', ecosystem: ['backend','python','api','web'],     tagline: 'Mikro-framework Python — minimalny rdzeń z rozszerzeniami według potrzeb.', website_url: 'https://flask.palletsprojects.com', license: 'BSD-3', language: 'Python' },

  // ─── BACKEND PHP ─────────────────────────
  { slug: 'laravel',      name: 'Laravel',      github: 'laravel/laravel',         npm: null,            category_slug: 'backend', ecosystem: ['backend','php','web','cms'],        tagline: 'Elegancki full-stack framework PHP z ORM Eloquent, kolejkami, broadcastingiem i Livewire.', website_url: 'https://laravel.com', license: 'MIT', language: 'PHP' },
  { slug: 'symfony',      name: 'Symfony',      github: 'symfony/symfony',         npm: null,            category_slug: 'backend', ecosystem: ['backend','php','enterprise'],       tagline: 'Zestaw wielokrotnego użycia komponentów PHP i framework dla aplikacji enterprise.', website_url: 'https://symfony.com', license: 'MIT', language: 'PHP' },

  // ─── BACKEND GO ──────────────────────────
  { slug: 'gin',          name: 'Gin',          github: 'gin-gonic/gin',           npm: null,            category_slug: 'backend', ecosystem: ['backend','go','api'],               tagline: 'Najszybszy framework webowy Go z minimalistycznym API i wydajnością ~40k req/s.', website_url: 'https://gin-gonic.com', license: 'MIT', language: 'Go' },
  { slug: 'echo',         name: 'Echo',         github: 'labstack/echo',           npm: null,            category_slug: 'backend', ecosystem: ['backend','go','api'],               tagline: 'Wysokowydajny, minimalistyczny framework Go z bogatym routingiem i middleware.', website_url: 'https://echo.labstack.com', license: 'MIT', language: 'Go' },
  { slug: 'fiber',        name: 'Fiber',        github: 'gofiber/fiber',           npm: null,            category_slug: 'backend', ecosystem: ['backend','go','api'],               tagline: 'Framework Go inspirowany Express.js — zbudowany na fasthttp, jeden z najszybszych.', website_url: 'https://gofiber.io', license: 'MIT', language: 'Go' },

  // ─── BACKEND RUST ────────────────────────
  { slug: 'axum',         name: 'Axum',         github: 'tokio-rs/axum',           npm: null,            category_slug: 'backend', ecosystem: ['backend','rust','api'],             tagline: 'Ergonomiczny framework webowy Rust od twórców Tokio — async-first z extract/handler pattern.', website_url: 'https://github.com/tokio-rs/axum', license: 'MIT', language: 'Rust' },
  { slug: 'actix-web',    name: 'Actix Web',    github: 'actix/actix-web',         npm: null,            category_slug: 'backend', ecosystem: ['backend','rust','api'],             tagline: 'Jeden z najszybszych frameworków webowych na świecie — actor model w Rust.', website_url: 'https://actix.rs', license: 'MIT', language: 'Rust' },

  // ─── BACKEND JAVA/KOTLIN ──────────────────
  { slug: 'spring-boot',  name: 'Spring Boot',  github: 'spring-projects/spring-boot', npm: null,        category_slug: 'backend', ecosystem: ['backend','java','enterprise'],      tagline: 'Najpopularniejszy framework Java do budowania mikroserwisów i aplikacji enterprise.', website_url: 'https://spring.io/projects/spring-boot', license: 'Apache-2.0', language: 'Java' },
  { slug: 'quarkus',      name: 'Quarkus',      github: 'quarkusio/quarkus',       npm: null,            category_slug: 'backend', ecosystem: ['backend','java','cloud','native'],  tagline: 'Kubernetes-native Java stack — błyskawiczny start i minimalne zużycie pamięci.', website_url: 'https://quarkus.io', license: 'Apache-2.0', language: 'Java' },
  { slug: 'ktor',         name: 'Ktor',         github: 'ktorio/ktor',             npm: null,            category_slug: 'backend', ecosystem: ['backend','kotlin','async'],         tagline: 'Asynchroniczny framework Kotlin od JetBrains do budowania serwerów i klientów HTTP.', website_url: 'https://ktor.io', license: 'Apache-2.0', language: 'Kotlin' },

  // ─── BAZY DANYCH SQL ─────────────────────
  { slug: 'postgresql',   name: 'PostgreSQL',   github: 'postgres/postgres',       npm: 'pg',            category_slug: 'databases', ecosystem: ['database','sql','relational'],      tagline: 'Najpotężniejsza open-source relacyjna baza danych z obsługą JSON, FTS i rozszerzeń.', website_url: 'https://www.postgresql.org', license: 'PostgreSQL', language: 'C' },
  { slug: 'mysql',        name: 'MySQL',        github: 'mysql/mysql-server',      npm: 'mysql2',        category_slug: 'databases', ecosystem: ['database','sql','relational'],      tagline: 'Najpopularniejsza open-source baza SQL, fundament LAMP stack i aplikacji webowych.', website_url: 'https://www.mysql.com', license: 'GPL-2.0', language: 'C++' },
  { slug: 'sqlite',       name: 'SQLite',       github: 'sqlite/sqlite',           npm: 'better-sqlite3', category_slug: 'databases', ecosystem: ['database','sql','embedded'],      tagline: 'Bezserwerowa baza SQL osadzona w pliku — idealna do aplikacji lokalnych i edge.', website_url: 'https://www.sqlite.org', license: 'Public Domain', language: 'C' },
  { slug: 'cockroachdb',  name: 'CockroachDB',  github: 'cockroachdb/cockroach',   npm: null,            category_slug: 'databases', ecosystem: ['database','sql','distributed'],    tagline: 'Skalowalny, odporny na awarie distributed SQL — Postgres-compatible, geo-partitioned.', website_url: 'https://www.cockroachlabs.com', license: 'BSL', language: 'Go' },

  // ─── BAZY DANYCH NOSQL ───────────────────
  { slug: 'mongodb',      name: 'MongoDB',      github: 'mongodb/mongo',           npm: 'mongoose',      category_slug: 'databases', ecosystem: ['database','nosql','document'],      tagline: 'Dokumentowa baza NoSQL z elastycznym schematem JSON, skalowalna horyzontalnie.', website_url: 'https://www.mongodb.com', license: 'SSPL', language: 'C++' },
  { slug: 'redis',        name: 'Redis',        github: 'redis/redis',             npm: 'ioredis',       category_slug: 'databases', ecosystem: ['database','cache','pubsub','queue'], tagline: 'In-memory data store — cache, pub/sub, kolejki i sesje w jednym z prędkością submilisekundową.', website_url: 'https://redis.io', license: 'RSAL', language: 'C' },
  { slug: 'supabase',     name: 'Supabase',     github: 'supabase/supabase',       npm: '@supabase/supabase-js', category_slug: 'databases', ecosystem: ['database','backend','baas'], tagline: 'Open-source Firebase alternative — PostgreSQL, Auth, Storage i Realtime w jednym.', website_url: 'https://supabase.com', license: 'Apache-2.0', language: 'TypeScript' },
  { slug: 'planetscale',  name: 'PlanetScale',  github: 'planetscale/vitess',      npm: null,            category_slug: 'databases', ecosystem: ['database','sql','serverless'],     tagline: 'Serverless MySQL platforma zbudowana na Vitess — branching schematów jak w Git.', website_url: 'https://planetscale.com', license: 'Apache-2.0', language: 'Go' },
  { slug: 'neon',         name: 'Neon',         github: 'neondatabase/neon',       npm: '@neondatabase/serverless', category_slug: 'databases', ecosystem: ['database','sql','serverless'], tagline: 'Serverless PostgreSQL z branch\'owaniem, autoscaling do zera i HTTP API dla edge.', website_url: 'https://neon.tech', license: 'Apache-2.0', language: 'Rust' },

  // ─── VECTOR DATABASES ────────────────────
  { slug: 'pinecone',     name: 'Pinecone',     github: null,                      npm: '@pinecone-database/pinecone', category_slug: 'databases', ecosystem: ['database','vector','ml','ai'], tagline: 'Managed vector database do semantic search i RAG — skaluje do miliardów wektorów.', website_url: 'https://www.pinecone.io', license: 'Proprietary', language: null },
  { slug: 'weaviate',     name: 'Weaviate',     github: 'weaviate/weaviate',       npm: 'weaviate-client', category_slug: 'databases', ecosystem: ['database','vector','ml','ai'],    tagline: 'Open-source vector search engine z GraphQL API i wbudowanymi modelami ML.', website_url: 'https://weaviate.io', license: 'BSD-3', language: 'Go' },
  { slug: 'qdrant',       name: 'Qdrant',       github: 'qdrant/qdrant',           npm: '@qdrant/js-client-rest', category_slug: 'databases', ecosystem: ['database','vector','ml'], tagline: 'Vector database w Rust — filtrowanie payload, sparse vectors i on-disk storage.', website_url: 'https://qdrant.tech', license: 'Apache-2.0', language: 'Rust' },
  { slug: 'pgvector',     name: 'pgvector',     github: 'pgvector/pgvector',       npm: null,            category_slug: 'databases', ecosystem: ['database','vector','postgresql'],  tagline: 'Rozszerzenie PostgreSQL do przechowywania wektorów i similarity search — zero nowego DB.', website_url: 'https://github.com/pgvector/pgvector', license: 'PostgreSQL', language: 'C' },

  // ─── ORM / QUERY BUILDERS ────────────────
  { slug: 'prisma',       name: 'Prisma',       github: 'prisma/prisma',           npm: 'prisma',        category_slug: 'databases', ecosystem: ['database','orm','typescript'],      tagline: 'Next-gen ORM TypeScript z auto-generowanym klientem, migracjami i Prisma Studio.', website_url: 'https://www.prisma.io', license: 'Apache-2.0', language: 'TypeScript' },
  { slug: 'drizzle',      name: 'Drizzle ORM',  github: 'drizzle-team/drizzle-orm', npm: 'drizzle-orm',  category_slug: 'databases', ecosystem: ['database','orm','typescript'],     tagline: 'Lekki ORM TypeScript-first z headless podejściem i zero runtime overhead.', website_url: 'https://orm.drizzle.team', license: 'Apache-2.0', language: 'TypeScript' },
  { slug: 'kysely',       name: 'Kysely',       github: 'kysely-org/kysely',       npm: 'kysely',        category_slug: 'databases', ecosystem: ['database','query-builder','typescript'], tagline: 'Type-safe query builder SQL z pełną inferencją typów — żaden błąd zapytania nie prześlizgnie się w kompilacji.', website_url: 'https://kysely.dev', license: 'MIT', language: 'TypeScript' },

  // ─── DEVOPS / CLOUD ──────────────────────
  { slug: 'docker',       name: 'Docker',       github: 'docker/cli',              npm: null,            category_slug: 'devops', ecosystem: ['devops','containers','cloud'],        tagline: 'Platforma konteneryzacji aplikacji — build once, run anywhere z izolowanymi środowiskami.', website_url: 'https://www.docker.com', license: 'Apache-2.0', language: 'Go' },
  { slug: 'kubernetes',   name: 'Kubernetes',   github: 'kubernetes/kubernetes',   npm: null,            category_slug: 'devops', ecosystem: ['devops','orchestration','cloud'],     tagline: 'System orkiestracji kontenerów Google — automatyczne skalowanie, self-healing i rolling updates.', website_url: 'https://kubernetes.io', license: 'Apache-2.0', language: 'Go' },
  { slug: 'terraform',    name: 'Terraform',    github: 'hashicorp/terraform',     npm: null,            category_slug: 'devops', ecosystem: ['devops','iac','cloud'],               tagline: 'Infrastructure as Code — deklaratywne zarządzanie infrastrukturą na 300+ providerach chmurowych.', website_url: 'https://www.terraform.io', license: 'BSL', language: 'Go' },
  { slug: 'ansible',      name: 'Ansible',      github: 'ansible/ansible',         npm: null,            category_slug: 'devops', ecosystem: ['devops','automation','iac'],          tagline: 'Agentless automation tool do provisioningu, konfiguracji i deploymentu przez SSH + YAML.', website_url: 'https://www.ansible.com', license: 'GPL-3.0', language: 'Python' },
  { slug: 'github-actions', name: 'GitHub Actions', github: 'actions/runner',     npm: null,            category_slug: 'devops', ecosystem: ['devops','ci-cd','automation'],        tagline: 'Natywne CI/CD GitHub — workflows w YAML, marketplace akcji i integracja z całym ekosystemem GitHub.', website_url: 'https://github.com/features/actions', license: 'MIT', language: 'Go' },
  { slug: 'argocd',       name: 'ArgoCD',       github: 'argoproj/argo-cd',        npm: null,            category_slug: 'devops', ecosystem: ['devops','gitops','kubernetes'],       tagline: 'GitOps continuous delivery dla Kubernetes — deklaratywny stan aplikacji z Git jako source of truth.', website_url: 'https://argo-cd.readthedocs.io', license: 'Apache-2.0', language: 'Go' },
  { slug: 'prometheus',   name: 'Prometheus',   github: 'prometheus/prometheus',   npm: null,            category_slug: 'devops', ecosystem: ['devops','monitoring','metrics'],      tagline: 'System monitoringu z time-series DB, PromQL i alertami — standard dla Kubernetes.', website_url: 'https://prometheus.io', license: 'Apache-2.0', language: 'Go' },
  { slug: 'grafana',      name: 'Grafana',      github: 'grafana/grafana',         npm: null,            category_slug: 'devops', ecosystem: ['devops','monitoring','visualization'], tagline: 'Platforma do wizualizacji metryk i logów — dashboardy dla Prometheus, Loki i 50+ źródeł.', website_url: 'https://grafana.com', license: 'AGPL-3.0', language: 'Go' },
  { slug: 'nginx',        name: 'NGINX',        github: 'nginx/nginx',             npm: null,            category_slug: 'devops', ecosystem: ['devops','web-server','proxy'],        tagline: 'Serwer HTTP, reverse proxy i load balancer — obsługuje ponad 40% stron w internecie.', website_url: 'https://nginx.org', license: 'BSD-2', language: 'C' },

  // ─── AI / ML ─────────────────────────────
  { slug: 'pytorch',      name: 'PyTorch',      github: 'pytorch/pytorch',         npm: null,            category_slug: 'ai-ml', ecosystem: ['ml','ai','research','python'],        tagline: 'Dominujący framework deep learning w badaniach — dynamiczny graph obliczeniowy i natywne GPU.', website_url: 'https://pytorch.org', license: 'BSD-3', language: 'Python' },
  { slug: 'tensorflow',   name: 'TensorFlow',   github: 'tensorflow/tensorflow',   npm: null,            category_slug: 'ai-ml', ecosystem: ['ml','ai','production','python'],      tagline: 'Framework ML Google — od prototypowania do produkcyjnego deploymentu na CPU/GPU/TPU.', website_url: 'https://www.tensorflow.org', license: 'Apache-2.0', language: 'Python' },
  { slug: 'scikit-learn', name: 'scikit-learn', github: 'scikit-learn/scikit-learn', npm: null,          category_slug: 'ai-ml', ecosystem: ['ml','python','data','classical'],     tagline: 'Kompletna biblioteka ML Python dla klasycznych algorytmów — klasyfikacja, regresja, clustering.', website_url: 'https://scikit-learn.org', license: 'BSD-3', language: 'Python' },
  { slug: 'langchain',    name: 'LangChain',    github: 'langchain-ai/langchain',  npm: 'langchain',     category_slug: 'ai-ml', ecosystem: ['ai','llm','python','agents'],         tagline: 'Framework do budowania aplikacji z LLM — chains, agents, RAG i integracje z 50+ modelami.', website_url: 'https://www.langchain.com', license: 'MIT', language: 'Python' },
  { slug: 'huggingface',  name: 'Hugging Face', github: 'huggingface/transformers', npm: null,           category_slug: 'ai-ml', ecosystem: ['ai','ml','nlp','models'],             tagline: 'Platforma ML z hub\'em 500k+ modeli, Transformers library i Spaces do deploymentu.', website_url: 'https://huggingface.co', license: 'Apache-2.0', language: 'Python' },
  { slug: 'openai-api',   name: 'OpenAI API',   github: 'openai/openai-python',    npm: 'openai',        category_slug: 'ai-ml', ecosystem: ['ai','llm','api'],                    tagline: 'API dostępu do GPT-4, DALL-E, Whisper i Embeddings — najszerzej używane LLM API na świecie.', website_url: 'https://platform.openai.com', license: 'Proprietary', language: null },
  { slug: 'anthropic-api', name: 'Anthropic API', github: 'anthropics/anthropic-sdk-python', npm: '@anthropic-ai/sdk', category_slug: 'ai-ml', ecosystem: ['ai','llm','api'],  tagline: 'API Claude — bezpieczne LLM z 200k context window, function calling i vision.', website_url: 'https://www.anthropic.com', license: 'MIT', language: null },
  { slug: 'llamaindex',   name: 'LlamaIndex',   github: 'run-llama/llama_index',   npm: 'llamaindex',    category_slug: 'ai-ml', ecosystem: ['ai','llm','rag','python'],            tagline: 'Framework do budowania RAG i data-augmented LLM applications z łatwą indeksacją.', website_url: 'https://www.llamaindex.ai', license: 'MIT', language: 'Python' },
  { slug: 'ollama',       name: 'Ollama',       github: 'ollama/ollama',           npm: null,            category_slug: 'ai-ml', ecosystem: ['ai','llm','local','selfhosted'],      tagline: 'Uruchamiaj LLM lokalnie (Llama 3, Mistral, Gemma) z prostym CLI i REST API.', website_url: 'https://ollama.com', license: 'MIT', language: 'Go' },

  // ─── NARZĘDZIA BUILD ─────────────────────
  { slug: 'vite',         name: 'Vite',         github: 'vitejs/vite',             npm: 'vite',          category_slug: 'tools', ecosystem: ['frontend','build','tooling'],         tagline: 'Nowej generacji bundler — natywne ESM w dev, Rollup w produkcji, błyskawiczny HMR.', website_url: 'https://vitejs.dev', license: 'MIT', language: 'TypeScript' },
  { slug: 'webpack',      name: 'Webpack',      github: 'webpack/webpack',         npm: 'webpack',       category_slug: 'tools', ecosystem: ['frontend','build','tooling'],         tagline: 'Dominujący bundler JavaScript — moduły, code splitting i loader ecosystem.', website_url: 'https://webpack.js.org', license: 'MIT', language: 'JavaScript' },
  { slug: 'esbuild',      name: 'esbuild',      github: 'evanw/esbuild',           npm: 'esbuild',       category_slug: 'tools', ecosystem: ['frontend','build','tooling'],         tagline: 'Ekstremalnie szybki bundler JavaScript napisany w Go — 100x szybszy od Webpacka.', website_url: 'https://esbuild.github.io', license: 'MIT', language: 'Go' },
  { slug: 'turbopack',    name: 'Turbopack',    github: 'vercel/turbo',            npm: null,            category_slug: 'tools', ecosystem: ['frontend','build','tooling'],         tagline: 'Następca Webpacka od Vercel napisany w Rust — inkrementalne budowanie dla Next.js 15.', website_url: 'https://turbo.build/pack', license: 'MPL-2.0', language: 'Rust' },
  { slug: 'bun',          name: 'Bun',          github: 'oven-sh/bun',             npm: null,            category_slug: 'tools', ecosystem: ['backend','runtime','tooling'],        tagline: 'All-in-one JavaScript runtime — 3x szybszy od Node.js, wbudowany bundler i test runner.', website_url: 'https://bun.sh', license: 'MIT', language: 'Zig' },
  { slug: 'deno',         name: 'Deno',         github: 'denoland/deno',           npm: null,            category_slug: 'tools', ecosystem: ['backend','runtime','edge'],           tagline: 'Bezpieczny runtime JavaScript/TypeScript od twórcy Node.js z natywnym TypeScript i permission system.', website_url: 'https://deno.com', license: 'MIT', language: 'Rust' },
  { slug: 'biome',        name: 'Biome',        github: 'biomejs/biome',           npm: '@biomejs/biome', category_slug: 'tools', ecosystem: ['frontend','linting','formatting'],  tagline: 'Szybki formatter i linter JS/TS napisany w Rust — zastępuje ESLint + Prettier w jednym narzędziu.', website_url: 'https://biomejs.dev', license: 'MIT', language: 'Rust' },

  // ─── TESTING ─────────────────────────────
  { slug: 'vitest',       name: 'Vitest',       github: 'vitest-dev/vitest',       npm: 'vitest',        category_slug: 'testing', ecosystem: ['testing','frontend','vite'],         tagline: 'Natywny test runner Vite — Vitest API kompatybilny z Jest, HMR dla testów, zero config.', website_url: 'https://vitest.dev', license: 'MIT', language: 'TypeScript' },
  { slug: 'playwright',   name: 'Playwright',   github: 'microsoft/playwright',    npm: '@playwright/test', category_slug: 'testing', ecosystem: ['testing','e2e','browser'],      tagline: 'Framework Microsoft do e2e testów — Chromium, Firefox, WebKit w jednym API z trace viewer.', website_url: 'https://playwright.dev', license: 'Apache-2.0', language: 'TypeScript' },
  { slug: 'jest',         name: 'Jest',         github: 'jestjs/jest',             npm: 'jest',          category_slug: 'testing', ecosystem: ['testing','javascript'],              tagline: 'Najpopularniejszy framework testów JavaScript od Meta z zero-config i snapshot testing.', website_url: 'https://jestjs.io', license: 'MIT', language: 'JavaScript' },
  { slug: 'cypress',      name: 'Cypress',      github: 'cypress-io/cypress',      npm: 'cypress',       category_slug: 'testing', ecosystem: ['testing','e2e','browser'],           tagline: 'E2E testing tool z wbudowanym time-travel debuggerem i real-time reload.', website_url: 'https://www.cypress.io', license: 'MIT', language: 'JavaScript' },
  { slug: 'pytest',       name: 'pytest',       github: 'pytest-dev/pytest',       npm: null,            category_slug: 'testing', ecosystem: ['testing','python'],                  tagline: 'Standardowy framework testów Python z fixture system, parametryzacją i rozbudowanym ekosystemem pluginów.', website_url: 'https://pytest.org', license: 'MIT', language: 'Python' },

  // ─── MOBILE ──────────────────────────────
  { slug: 'flutter',      name: 'Flutter',      github: 'flutter/flutter',         npm: null,            category_slug: 'mobile', ecosystem: ['mobile','ui','cross-platform'],      tagline: 'Google UI toolkit do budowania aplikacji na iOS, Android, Web i Desktop z jednej bazy kodu.', website_url: 'https://flutter.dev', license: 'BSD-3', language: 'Dart' },
  { slug: 'react-native', name: 'React Native', github: 'facebook/react-native',   npm: 'react-native',  category_slug: 'mobile', ecosystem: ['mobile','javascript','cross-platform'], tagline: 'Framework Meta do budowania natywnych aplikacji iOS i Android w React z JSX.', website_url: 'https://reactnative.dev', license: 'MIT', language: 'JavaScript' },
  { slug: 'expo',         name: 'Expo',         github: 'expo/expo',               npm: 'expo',          category_slug: 'mobile', ecosystem: ['mobile','react-native','tooling'],   tagline: 'Platform i toolkit dla React Native — managed workflow, EAS Build i OTA updates.', website_url: 'https://expo.dev', license: 'MIT', language: 'TypeScript' },

  // ─── PLATFORMY / SAAS ────────────────────
  { slug: 'vercel',       name: 'Vercel',       github: 'vercel/vercel',           npm: 'vercel',        category_slug: 'platforms', ecosystem: ['hosting','edge','frontend','serverless'], tagline: 'Platforma do deploymentu Next.js i frontendu — CDN edge, preview deploys i zero-config CI.', website_url: 'https://vercel.com', license: 'Apache-2.0', language: 'Go' },
  { slug: 'cloudflare-workers', name: 'Cloudflare Workers', github: 'cloudflare/workerd', npm: 'wrangler', category_slug: 'platforms', ecosystem: ['edge','serverless','cdn'],    tagline: 'Serverless JavaScript na edge Cloudflare — 0ms cold start, 300+ lokalizacji, 100k req/day free.', website_url: 'https://workers.cloudflare.com', license: 'Apache-2.0', language: 'C++' },
  { slug: 'stripe',       name: 'Stripe',       github: 'stripe/stripe-node',      npm: 'stripe',        category_slug: 'platforms', ecosystem: ['payments','saas','api'],             tagline: 'Kompletna platforma płatności — API, webhooks, subscriptions, Connect i Radar fraud detection.', website_url: 'https://stripe.com', license: 'MIT', language: null },

  // ─── CMS ─────────────────────────────────
  { slug: 'wordpress',    name: 'WordPress',    github: 'WordPress/WordPress',     npm: null,            category_slug: 'cms', ecosystem: ['cms','php','web'],                      tagline: 'Najpopularniejszy CMS świata — napędza 43% stron WWW z bogatym ekosystemem pluginów.', website_url: 'https://wordpress.org', license: 'GPL-2.0', language: 'PHP' },
  { slug: 'strapi',       name: 'Strapi',       github: 'strapi/strapi',           npm: '@strapi/strapi', category_slug: 'cms', ecosystem: ['cms','headless','nodejs','api'],       tagline: 'Open-source headless CMS Node.js z admin panelem, REST/GraphQL API i plugin system.', website_url: 'https://strapi.io', license: 'MIT', language: 'JavaScript' },
  { slug: 'contentful',   name: 'Contentful',   github: null,                      npm: 'contentful',    category_slug: 'cms', ecosystem: ['cms','headless','saas'],                tagline: 'SaaS headless CMS z rich content modeling, multi-language i GraphQL Content API.', website_url: 'https://www.contentful.com', license: 'Proprietary', language: null },
  { slug: 'sanity',       name: 'Sanity',       github: 'sanity-io/sanity',        npm: '@sanity/client', category_slug: 'cms', ecosystem: ['cms','headless','react'],              tagline: 'Headless CMS z real-time collaboration, GROQ query language i Portable Text.', website_url: 'https://www.sanity.io', license: 'MIT', language: 'JavaScript' },
]
